apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "health-auto-export-server.fullname" . }}-mongodb-data
  labels:
    io.kompose.service: mongodb-data
  {{- include "health-auto-export-server.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mongodbData.storageRequest | quote }}
