apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "website.fullname" . }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  hostnames:
  - {{ .Values.hostname }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: {{ include "website.fullname" . }}
      port: {{ .Values.service.port }}
      kind: Service
      weight: 1

