apiVersion: v2
name: database
description: Wrapper chart to deploy the Postgres Helm chart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: "https://charts.bitnami.com/bitnami"
